linters:
  Comment:
    enabled: false
  DuplicateProperty:
    enabled: false # necessary for fallback properties, like font-size (px and rem) and height (px and vh)
  Indentation:
    enabled: false
  SelectorDepth:
    max_depth: 4
  SelectorFormat:
    enabled: false # disabled for disqus and lasso
  SpaceBeforeBrace:
    enabled: false # disabled for "social-icon" mixin
